### PR TITLE
Fix - Add missing surface colors

### LINKED ISSUE #111: dynamicColorScheme() doesn't specify any value for some of the surface* color attributes
The `ColorScheme(...)` constructor that is used in `dynamicColorScheme()` leaves the following color attributes unspecified, and their corresponding methods in `MaterialDynamicColors` class are not utilized there:
```
        surfaceBright = Color.Unspecified,
        surfaceDim = Color.Unspecified,
        surfaceContainer = Color.Unspecified,
        surfaceContainerHigh = Color.Unspecified,
        surfaceContainerHighest = Color.Unspecified,
        surfaceContainerLow = Color.Unspecified,
        surfaceContainerLowest = Color.Unspecified,
```

```
public class MaterialDynamicColors {
    ....
    public fun surfaceBright(): DynamicColor = DynamicColor(...)
    public fun surfaceDim(): DynamicColor = DynamicColor(...)
    public fun surfaceContainer(): DynamicColor = DynamicColor(...)
    public fun surfaceContainerHigh(): DynamicColor = DynamicColor(...)
    public fun surfaceContainerHighest(): DynamicColor = DynamicColor(...)
    public fun surfaceContainerLow(): DynamicColor = DynamicColor(...)
    public fun surfaceContainerLowest(): DynamicColor = DynamicColor(...)
}
```

By utilizing the main constructor of `ColorScheme(...)`, the above missing attributes can be specified there.

### PR DESCRIPTION
**Pull request by jordond**
Closes #111

### CODE REVIEW

File: material-kolor/src/commonMain/kotlin/com/materialkolor/DynamicColorScheme.kt [hunk 1]
```diff
@@ -74,6 +74,13 @@ public fun dynamicColorScheme(
         secondaryContainer = colors.secondaryContainer().getColor(scheme),
         surface = colors.surface().getColor(scheme),
         surfaceTint = colors.surfaceTint().getColor(scheme),
+        surfaceBright = colors.surfaceBright().getColor(scheme),
+        surfaceDim = colors.surfaceDim().getColor(scheme),
+        surfaceContainer = colors.surfaceContainer().getColor(scheme),
+        surfaceContainerHigh = colors.surfaceContainer().getColor(scheme),
```
Comment (kirill-grouchnikov) [inline material-kolor/src/commonMain/kotlin/com/materialkolor/DynamicColorScheme.kt:80]: This should be surfaceContainerHigh().getColor...

**Review by kirill-grouchnikov — COMMENTED** [review]
See comment on line 80
